sudo: required
language: python3.6
services:
  - docker
env:
  matrix:
    - IMAGE=nthienan/alpine VERSION=3.9.2-2 DIR=alpine
    - IMAGE=nthienan/jenkins VERSION=2.176-2 DIR=jenkins
    - IMAGE=nthienan/grafana VERSION=6.1.6-1 DIR=grafana
    - IMAGE=nthienan/yamllint VERSION=1.16.0-1 DIR=yamllint
install: true

script:
  - ./builder.sh build $IMAGE $VERSION $DIR
after_success:
  - docker images

before_deploy:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
deploy:
  - provider: script
    script: ./builder.sh deploy $IMAGE $VERSION
    on:
      branch: master
after_deploy:
  - docker images
